services:
  postgres:
    container_name: storage
    image: postgres:13.3
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "music_lib"

    ports:
      - "5432:5432"
    networks:
      - netw

  #
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    hostname: app
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - netw

networks:
  netw:
    name: custom_netw
    driver: bridge
    external: true

volumes:
  pgdata:
